nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*'] # Permite todas as origens (não recomendado para produção)
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600